version: '3.8'

services:
 api:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app

 mobsf:
  image: opensecurity/mobile-security-framework-mobsf
  ports:
  - 8000:8000
  environment:
  - MOBSF_API_KEY=apikey123
